server:
  name: "project-api"
  addr: "192.168.1.1:9080"
zap:
  debugFileName: ".\\logs\\debug\\project-debug.log"
  infoFileName: ".\\logs\\info\\project-info.log"
  warnFileName: ".\\logs\\error\\project-error.log"
  maxSize: 500,
  maxAge: 28,
  MaxBackups: 3
etcd:
  addrs:
    - "192.168.1.3:2379"